config/routes.rb
Rails.application.routes.draw do
  resources :static_pages, :only => [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/q', to: "static_pages#index"
  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'flickr'
  def index
    @flickr = Flickr.new
    if request.query_string.present? 
      @user_id = params[:user][:id]
      @photos = @flickr.people.getPhotos(:user_id => @user_id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar content-padding">
    <p class="flex g-10"> <span class="flex"><%= image_tag("flickr-logo.png", id: "logo", class: "al-c") %></span>flickr API</p>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="content-padding">
  <div class="nl-padding">
    <h2>Fazer busca:</h2>
    <%= form_for :user, url: q_path, method: :get do |form| %>
      <%= form.text_field :id %>
      <%= form.submit 'search'%>
    <% end %>
    <div class="nl-padding">
    <% @photos.each do |photo| %>

      <% info = @flickr.photos.getInfo(:photo_id => photo.id) %>
      <%= image_tag Flickr.url_n(info) %>
    <% end %>
    </div>
  </div>
</div>